REQUIRED_SECRET_KEYS = {
    "aws": [
        "aws_access_key_id",
        "aws_secret_access_key",
    ],
    "azure": [
        "tenant_id",
        "client_secret",
        "client_id",
    ],
    "google_cloud": [
        "type",
        "project_id",
        "private_key_id",
        "private_key",
        "client_email",
        "client_id",
        "auth_uri",
        "token_uri",
        "auth_provider_x509_cert_url",
        "client_x509_cert_url",
        "universe_domain",
    ],
}

SEVERITIES = {
    "Critical": "critical",
    "High": "high",
    "Medium": "medium",
    "Low": "low",
    "Informational": "informational",
}

SEVERITY_MAP = {
    "Critical": "CRITICAL",
    "High": "HIGH",
    "Medium": "MEDIUM",
    "Low": "LOW",
    "Informational": "INFORMATIONAL",
}

SEVERITY_SCORE_MAP = {
    "CRITICAL": 4,
    "HIGH": 3,
    "MEDIUM": 2,
    "LOW": 1,
    "INFORMATIONAL": 0,
    "UNKNOWN": 1,
}

COMPLIANCE_FRAMEWORKS = {
    "aws": {
        "CIS-1.4": "cis_1.4_aws",
        "CIS-1.5": "cis_1.5_aws",
        "CIS-2.0": "cis_2.0_aws",
        "CIS-3.0": "cis_3.0_aws",
        "CISA": "cisa_aws",
        "SOC2": "soc2_aws",
        "MITRE-ATTACK": "mitre_attack_aws",
        "GDPR": "gdpr_aws",
        "HIPAA": "hipaa_aws",
        "AWS-Account-Security-Onboarding": "aws_account_security_onboarding_aws",
        "AWS-Foundational-Security-Best-Practices": "aws_foundational_security_best_practices_aws",
        "AWS-Foundational-Technical-Review": "aws_foundational_technical_review_aws",
        "AWS-Well-Architected-Framework-Reliability-Pillar": "aws_well_architected_framework_reliability_pillar_aws",
        "AWS-Well-Architected-Framework-Security-Pillar": "aws_well_architected_framework_security_pillar_aws",
        "AWS-Audit-Manager-Control-Tower-Guardrails": "aws_audit_manager_control_tower_guardrails_aws",
        "GxP-21-CFR-Part-11": "gxp_21_cfr_part_11_aws",
        "GxP-EU-Annex-11": "gxp_eu_annex_11_aws",
        "NIST-800-171-Revision-2": "nist_800_171_revision_2_aws",
        "NIST-800-53-Revision-4": "nist_800_53_revision_4_aws",
        "NIST-800-53-Revision-5": "nist_800_53_revision_5_aws",
        "ENS-RD2022": "ens_rd2022_aws",
        "NIST-CSF-1.1": "nist_csf_1.1_aws",
        "RBI-Cyber-Security-Framework": "rbi_cyber_security_framework_aws",
        "FFIEC": "ffiec_aws",
        "PCI-3.2.1": "pci_3.2.1_aws",
        "FedRamp-Moderate-Revision-4": "fedramp_moderate_revision_4_aws",
        "FedRAMP-Low-Revision-4": "fedramp_low_revision_4_aws",
        "ISO27001-2013": "iso27001_2013_aws",
    },
    "google_cloud": {
        "CIS-2.0": "cis_2.0_gcp",
        "MITRE-ATTACK": "mitre_attack_gcp",
    },
    "azure": {
        "CIS-2.0": "cis_2.0_azure",
        "CIS-2.1": "cis_2.1_azure",
        "MITRE-ATTACK": "mitre_attack_azure",
    },
    "kubernetes": {
        "CIS-1.8": "cis_1.8_kubernetes",
    },
}

REGIONS = {
    "aws": [
        "af-south-1",
        "ap-east-1",
        "ap-northeast-1",
        "ap-northeast-2",
        "ap-northeast-3",
        "ap-south-1",
        "ap-south-2",
        "ap-southeast-1",
        "ap-southeast-2",
        "ap-southeast-3",
        "ap-southeast-4",
        "ca-central-1",
        "ca-west-1",
        "cn-north-1",
        "cn-northwest-1",
        "eu-central-1",
        "eu-central-2",
        "eu-north-1",
        "eu-south-1",
        "eu-south-2",
        "eu-west-1",
        "eu-west-2",
        "eu-west-3",
        "il-central-1",
        "me-central-1",
        "me-south-1",
        "sa-east-1",
        "us-east-1",
        "us-east-2",
        "us-gov-east-1",
        "us-gov-west-1",
        "us-west-1",
        "us-west-2",
    ]
}

SERVICES = {
    "aws": {
        "AccessAnalyzer": "accessanalyzer",
        "Account": "account",
        "ACM": "acm",
        "APIGateway": "apigateway",
        "APIGatewayV2": "apigatewayv2",
        "AppStream": "appstream",
        "Athena": "athena",
        "AutoScaling": "autoscaling",
        "Lambda": "awslambda",
        "Backup": "backup",
        "CloudFormation": "cloudformation",
        "CloudFront": "cloudfront",
        "CloudTrail": "cloudtrail",
        "CloudWatch": "cloudwatch",
        "CodeArtifact": "codeartifact",
        "CodeBuild": "codebuild",
        "CognitoIDP": "cognito",
        "ConfigService": "config",
        "DirectoryService": "directoryservice",
        "Data Lifecycle Manager": "dlm",
        "DocumentDB": "documentdb",
        "DRS": "drs",
        "DynamoDB": "dynamodb",
        "EC2": "ec2",
        "ECR": "ecr",
        "ECS": "ecs",
        "EFS": "efs",
        "EKS": "eks",
        "Elasticache": "elasticache",
        "ELB": "elb",
        "ELBv2": "elbv2",
        "EMR": "emr",
        "EventBridge": "eventbridge",
        "FMS": "fms",
        "Glacier": "glacier",
        "Glue": "glue",
        "GuardDuty": "guardduty",
        "IAM": "iam",
        "Inspector2": "inspector2",
        "Kafka": "kafka",
        "KMS": "kms",
        "Lightsail": "lightsail",
        "Macie": "macie",
        "Neptune": "neptune",
        "NetworkFirewall": "networkfirewall",
        "OpenSearchService": "opensearch",
        "Organizations": "organizations",
        "RDS": "rds",
        "Redshift": "redshift",
        "ResourceExplorer2": "resourceexplorer2",
        "Route53": "route53",
        "S3": "s3",
        "SageMaker": "sagemaker",
        "SecretsManager": "secretsmanager",
        "SecurityHub": "securityhub",
        "Sheild": "shield",
        "SNS": "sns",
        "SQS": "sqs",
        "SSM": "ssm",
        "SSMIncidents": "ssmincidents",
        "StorageGateway": "storagegateway",
        "TrustedAdvisor": "trustedadvisor",
        "VPC": "vpc",
        "WAFv2": "wafv2",
        "WellArchitected": "wellarchitected",
        "WorkSpaces": "workspaces",
    },
    "google_cloud": {
        "API Keys": "apikeys",
        "artifacts": "artifacts",
        "BigQuery": "bigquery",
        "CloudSQL": "cloudsql",
        "CloudStorage": "cloudstorage",
        "ComputeEngine": "compute",
        "Dataproc": "dataproc",
        "DNS": "dns",
        "GCR": "gcr",
        "GKE": "gke",
        "IAM": "iam",
        "KMS": "kms",
        "Logging": "logging",
    },
    "azure": {
        "AKS (Azure Kubernetes Service)": "aks",
        "App": "app",
        "AppInsights": "appinsights",
        "CosmosDB": "cosmosdb",
        "Defender": "defender",
        "Entra": "entra",
        "IAM": "iam",
        "KeyVault": "keyvault",
        "Monitor": "monitor",
        "MySQL": "mysql",
        "Network": "network",
        "Policy": "policy",
        "PostgreSQL": "postgresql",
        "SQLServer": "sqlserver",
        "Storage": "storage",
        "VirtualMachines": "vm",
    },
}